---
- hosts: "{{ hostname }}"
  become: true
  tasks:
  - name: Copy file to server
    copy:
      src: "{{ source_dir }}"
      dest: "{{ dest_dir }}"
      owner: root
      group: root
      mode: 0644

  - name: "Create a watcher text file"
    file:
      dest: "{{ dest_txt_dir }}"
      state: touch

  - name: "Add cron job watcher to crontab"
    cron:
      name: "CronJobs Watcher"
      minute: "*"
      hour: "*"
      day: "*"
      weekday: "*"
      month: "*"
      job: "{{ job }}"
      backup: yes
